site:
  name: "SCode Portfolio"
_editables:
  - label: "Hero Section"
    selector: "header.hero-outer"
  - label: "About Section"
    selector: "section.about"
  - label: "Projects Section"
    selector: "section.projects"
  - label: "Contact Section"
    selector: "section.contact"
  - label: "Footer"
    selector: "footer.footer"
